spring:
  application:    name: EventGenerator
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: local_rabbit
        output:
          destination: queue.pretty.log.messages
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  kafka:    bootstrap-servers: localhost:9092
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ternium
      auto-index-creation: false
      expiration-duration: 15
      expiration-time-unit: MINUTES
server:
  port: 8081
kieserver:
  #url: http://localhost:8080/kie-server/services/rest/server
  url: http://localhost:8080/business-central/maven2/com/droolsrulesternium/ternium/1.0.0/ternium-1.0.0.jar
  user: wbadmin
  password: wbadmin
  container: ternium_1.0.0
  mainrulename: FilterRules
  translatoragendarule: Translator
logging:  logstash:    enabled: true
    host: 127.0.0.1
    port: 5000
    queue-size: 512  metrics:    logs:      enabled: false
      report-frequency: 60